Serialisation of prefabs when on window quit unity
LahessAimere/Classe3e_2024-2025-Exo2 pull request #4
Opened 2024-11-20 13:58 UTC by LahessAimere

2024-11-20 14:04 UTC, Logan-dlp requested changes
Essaye de trouver un autre emplacement de fichier car le fichier pourras créer des conflit et d'autre problème si tu le sauvegarde là

2024-11-20 14:04 UTC, Logan-dlp commented on Assets/Scripts/PrefabSpawnerWindow.cs
> +        private const string SaveFilePath = "Assets/Scripts/PrefabSpawnerData.json";
Je suis pas sur de la sécurité si tu le save ici

2024-11-20 14:04 UTC, Logan-dlp commented on Assets/Scripts/SavePrefabData.cs
> +        private const string SaveFilePath = "Assets/Scripts/PrefabSpawnerData.json";
En plus tu le répète

2024-11-26 11:15 UTC, LahessAimere commented on Assets/Scripts/PrefabSpawnerWindow.cs
> +        private const string SaveFilePath = "Assets/Scripts/PrefabSpawnerData.json";
Je vais changer ça

2024-11-26 11:25 UTC, LahessAimere commented
https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html

J'ai trouvé ça, je change et je t'envoie tu me diras ce que tu en penses

2024-11-26 13:24 UTC, merged